#!/bin/bash
#BSUB -J AppReClas_VAR_SUB
#BSUB -P acc_adolpvs
#BSUB -q premium
#BSUB -n 1
#BSUB -R "rusage[mem=4000]"
#BSUB -R "span[hosts=1]"
#BSUB -W 00:05
#BSUB -o /sc/orga/projects/adolpvs/PreProcPipeline/logs/ApplyHandReClassfications_3.27.0-Sinai/ApplyHandReClassfications_VAR_SUB.log
#BSUB -L /bin/bash

StudyFolder="/sc/orga/projects/adolpvs/Subjects/"
home="/sc/orga/projects/adolpvs/PreProcPipeline/"
scripts="$home/Scripts/HCPpipelines-3.27.0-Sinai/Examples/Scripts/"
hcpfix="$home/Scripts/HCPpipelines-3.27.0-Sinai/ICAFIX/"


# housekeeping so most recent log is obvious
logfile="$home/logs/ApplyHandReClassfications_3.27.0-Sinai/ApplyHandReClassfications_VAR_SUB.log"
if [[ -e "$logfile" ]] ; then
        mkdir -p $home/logs/ApplyHandReClassfications_3.27.0-Sinai/loghist
        cat $logfile >> $home/logs/ApplyHandReClassfications_3.27.0-Sinai/loghist/ApplyHandReClassfications_VAR_SUB.loghist
        rm $logfile
fi

# set up environment
module purge
. $scripts/SetUpGlobalDefaults.sh
. $scripts/SetUpMinervaModules.sh
. $scripts/SetUpHCPPipeline.sh

# run ApplyHandReClassfications.sh
sh $scripts/env_report.sh 2>&1
sh $hcpfix/ApplyHandReClassifications.sh --path=${StudyFolder} --subject=VAR_SUB --fmri-name=fMRI_merged --high-pass=2000  2>&1

